### ISSUE TITLE
Saving league state

### ISSUE THREAD

**Issue by 28raining** [teijo/jquery-group#4]
I'd like to use this league for table tennis, I've got it running in Firefox.

Could you supply instuctions on how to save the league, so that I can close and open it later? Or is this not possible?

If not, could you at least supply us with an unminified code, it looks like all the function names have been compressed. Or could you tell us which variables hold the team names?

**Comment by teijo** [comment]
Hi,

> Could you supply instuctions on how to save the league, so that I can close and open it later? Or is this not possible?

The instructions are currently a bit unclear, but check out the save callback function on the demo page: http://www.aropupu.fi/group/

I.e. this:

``` javascript
$('#editor').group({
  init: testData,
  save: function(state) {
    // Reconstruct read-only version by initializing it with received state
    $('#view').empty().group({
      init: state
    })
  }
})
```

Save callback gets the state as argument [for saving]. You can use the same state to initialize the group again [for opening].

> If not, could you at least supply us with an unminified code

Unminified code is under `src/` of the project. It's written in SASS and CoffeeScript instead of CSS and JavaScript correspondingly: https://github.com/teijo/jquery-group/tree/master/src
